# Generated by Django 5.2.4 on 2025-08-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
