# Generated by Django 5.2.4 on 2025-09-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('can_change_category', 'Can change category')]},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='contact',
            field=models.CharField(max_length=300, verbose_name='mumero de telefono'),
        ),
    ]
