# Generated by Django 5.2.4 on 2025-08-12 02:25

from datetime import date
from django.db import migrations


class Migration(migrations.Migration):


    def create_initial_books(apps, schema_editor):
        Book = apps.get_model('app1', 'Book')

        Book.objects.create(title='El Señor de los Anillos', author='J.R.R. Tolkien', publication_date=date(1954, 7, 29))
        Book.objects.create(title='Cien Años de Soledad', author='Gabriel García Márquez', publication_date=date(1967, 5, 30))
        Book.objects.create(title='1984', author='George Orwell', publication_date=date(1949, 6, 8))


    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_books),
    ]
